FROM ruby:3.1.1

# Default directory
ENV INSTALL_PATH /opt/app
RUN mkdir -p $INSTALL_PATH

WORKDIR /opt/app

COPY ./backend/Gemfile /opt/app/Gemfile
COPY ./backend/Gemfile.lock /opt/app/Gemfile.lock
RUN bundle install
COPY ./backend/ /opt/app
EXPOSE 8010
# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0", "-p", "8010", "-e", "production"]
