FROM node:alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY ./frontend /usr/src/app
COPY ./frontend/package*.json /usr/src/app
COPY ./frontend/yarn.lock /usr/src/app

RUN yarn install

EXPOSE 3001

CMD ["yarn", "start"]