version: "3.9"

volumes:
  bundle:
  db:
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./backend/db:/root/db
    stdin_open: true
    tty: true
    ports:
      - '9000:9000'

  api:
    build:
      context: .
      dockerfile: Dockerfile.rails
    volumes:
      - ./backend:/opt/app
      - bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e production"
