version: "3.9"

volumes:
  bundle:
  db:
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./db:/root/db
    stdin_open: true
    tty: true
    ports:
      - '9000:9000'

  drkiq:
    build:
      context: .
      dockerfile: Dockerfile.rails
    volumes:
      - ./backend:/opt/app
      - bundle:/usr/local/bundle
    ports:
      - '8010:8010'
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8010 -b '0.0.0.0'"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - drkiq
    ports:
      - '8020:8020'
