name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Test secret ${{ secrets.TEST_SECRTE }}"
      - run: ls -a
      - run: cd ./backend
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      - name: Build and run tests
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:prepare
          bundle exec rspec
